apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    monitoring: enabled
    prometheus.io/scrape: "true"
  annotations:
    description: "Monitoring infrastructure namespace for Prometheus, Grafana, and AlertManager"