# Sponsor this Business Intelligence Platform
# Help support the development of this comprehensive AI-powered business analysis platform

# GitHub Sponsors (most popular for open source projects)
github: # [UMainLove] # Uncomment and add your GitHub username when you enable GitHub Sponsors

# Alternative platforms (uncomment and add your usernames as needed)
# patreon: # Your Patreon username
# ko_fi: # Your Ko-fi username  
# buy_me_a_coffee: # Your Buy Me a Coffee username
# liberapay: # Your Liberapay username
# open_collective: # Your Open Collective username

# Custom sponsorship links - Crypto donations accepted
# Multiple blockchain networks supported for maximum accessibility
custom: [
  'https://github.com/UMainLove/business_intelligence_platform/blob/main/CRYPTO_DONATIONS.md'
]