# Codecov configuration for Business Intelligence Platform
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: true
  max_report_age: "24h"

comment:
  behavior: default
  layout: reach,diff,flags,tree
  show_carryforward_flags: false

coverage:
  precision: 2
  range:
    - 60.0
    - 80.0
  round: down
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 80%

# Ignore paths
ignore:
  - "tests/"
  - "scripts/"
  - "k8s/"
  - "data/"
  - "*.md"
  - "requirements*.txt"
  - "Dockerfile"
  - "docker-compose.yml"
  - ".github/"