[tool.black]
line-length = 100
target-version = ["py39"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "N"]
ignore = ["E501"]  # Ignore line too long, let formatter handle it

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "S", "ANN", "PLR2004", "ARG"]
"*/__init__.py" = ["D", "F401"]
"src/business_intelligence.py" = ["C901"]  # Allow complexity for tool factory function

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.coverage.run]
source = ["src"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*",
    "*/migrations/*",
    "*/venv/*",
    "*/.venv/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod"
]
show_missing = true
precision = 2

[tool.coverage.xml]
output = "coverage.xml"