---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-keys
  namespace: business-intelligence
  labels:
    app: api-keys
  annotations:
    rotation.bitnami.com/enabled: "true"
    rotation.bitnami.com/schedule: "monthly"
spec:
  scope: namespace-wide
  encryptedData:
    # These are example encrypted values - in production, use kubeseal to encrypt actual values
    anthropic-api-key: AgAyMA...encrypted-anthropic-api-key...XYZ
    openai-api-key: AgAzNA...encrypted-openai-api-key...ABC
template:
  metadata:
    name: api-keys
    namespace: business-intelligence
    labels:
      app: api-keys
  type: Opaque
