# PostgreSQL Database for Business Intelligence Platform
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: business-intelligence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: business-intelligence
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10070  # High UID for security (based on postgres Alpine UID 70)
        fsGroup: 10070
      containers:
      - name: postgres
        image: postgres:16-alpine
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10070  # High UID for security (based on postgres Alpine UID 70)
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: business_intelligence
        - name: POSTGRES_USER
          value: bi_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bi-secrets
              key: postgres-password
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-tmp
          mountPath: /tmp
        - name: postgres-run
          mountPath: /var/run/postgresql
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U bi_user -d business_intelligence
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U bi_user -d business_intelligence
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-tmp
        emptyDir: {}
      - name: postgres-run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: business-intelligence
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP