# RBAC Configuration for Business Intelligence Platform
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bi-service-account
  namespace: business-intelligence

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: business-intelligence
  name: bi-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
# Note: Secret access removed for security. Use dedicated secret management roles if needed.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bi-role-binding
  namespace: business-intelligence
subjects:
- kind: ServiceAccount
  name: bi-service-account
  namespace: business-intelligence
roleRef:
  kind: Role
  name: bi-role
  apiGroup: rbac.authorization.k8s.io

---
# Network Policy for Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bi-network-policy
  namespace: business-intelligence
spec:
  podSelector:
    matchLabels:
      app: bi-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: grafana
    ports:
    - protocol: TCP
      port: 8501
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80