apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
            ephemeral-storage: 2Gi
          limits:
            memory: 8Gi
            cpu: 4000m
            ephemeral-storage: 20Gi
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus/'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'
        - '--storage.tsdb.retention.time=$(PROMETHEUS_RETENTION_TIME)'
        - '--storage.tsdb.retention.size=$(PROMETHEUS_RETENTION_SIZE)'
        - '--web.enable-admin-api'
        - '--web.route-prefix=/'
        - '--web.external-url=http://prometheus.monitoring:9090'
        - '--log.level=warn'
        - '--query.max-concurrency=50'
        - '--query.timeout=5m'
        - '--storage.tsdb.wal-compression'
        - '--storage.tsdb.min-block-duration=2h'
        - '--storage.tsdb.max-block-duration=24h'