apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base

patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
    target:
      kind: Deployment
      name: prometheus

configMapGenerator:
  - name: monitoring-env-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - DEBUG_MODE=false
      - METRICS_RETENTION_DAYS=14
      - ALERT_THROTTLE_MINUTES=10
      - ENABLE_PROFILING=false
      - PROMETHEUS_CONCURRENT_QUERIES=30
      - prometheus.retention.time=14d
      - prometheus.retention.size=50GB
      - prometheus.replicas=2
      - grafana.replicas=2
      - alertmanager.replicas=2
      - EMAIL_SMTP_HOST=localhost:587
      - EMAIL_FROM_ADDRESS=staging@bi-platform.local
  - name: environment-properties
    literals:
      - app.properties=ENVIRONMENT=staging

replicas:
  - name: prometheus
    count: 2
  - name: grafana
    count: 2
  - name: alertmanager
    count: 2