apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - grafana.yaml
  - alertmanager.yaml
  - prometheus-rules.yaml
  - monitoring-config.yaml
  - monitoring-secrets.yaml

configMapGenerator:
  - name: monitoring-env-config
    literals:
      - ENVIRONMENT=base
      - LOG_LEVEL=info
      - DEBUG_MODE=false
      - METRICS_RETENTION_DAYS=30
      - ALERT_THROTTLE_MINUTES=15
      - ENABLE_PROFILING=false
      - PROMETHEUS_CONCURRENT_QUERIES=20

commonLabels:
  monitoring.agentic-chat.ai/managed-by: kustomize
  monitoring.agentic-chat.ai/version: v1.0.0

namespace: monitoring

images:
  - name: prom/prometheus
    newTag: v2.40.0
  - name: grafana/grafana
    newTag: 9.3.0
  - name: prom/alertmanager
    newTag: v0.25.0