apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
  labels:
    app: monitoring
    component: configuration
type: Opaque
data:
  # Base64 encoded secrets
  grafana-admin-password: YWRtaW5AMTIzIyQ=  # admin@123#$
  prometheus-basic-auth-password: cHJvbWV0aGV1c0AxMjM=  # prometheus@123
  alertmanager-webhook-secret: d2ViaG9va1NlY3JldEAxMjM=  # webhookSecret@123
  slack-webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvWU9VUi9TTEFDS19VUkw=
  pagerduty-integration-key: WU9VUl9QQUdFUkRVVFlfS0VZ
  smtp-password: c210cFBhc3N3b3JkQDEyMw==  # smtpPassword@123
  s3-access-key: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  s3-secret-key: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==