apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10010
        fsGroup: 10010
      containers:
      - name: grafana
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10010
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m
        env:
        - name: GF_LOG_LEVEL
          value: "debug"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "true"  # Allow sign-up in dev
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"  # Enable anonymous access in dev
        volumeMounts:
        - name: grafana-tmp
          mountPath: /tmp
        - name: grafana-logs
          mountPath: /var/log/grafana
        - name: grafana-plugins
          mountPath: /var/lib/grafana/plugins
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: grafana-tmp
        emptyDir: {}
      - name: grafana-logs
        emptyDir: {}
      - name: grafana-plugins
        emptyDir: {}