apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10009
        fsGroup: 10009
      containers:
      - name: prometheus
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10009
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 1000m
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus/'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'
        - '--storage.tsdb.retention.time=$(PROMETHEUS_RETENTION_TIME)'
        - '--storage.tsdb.retention.size=$(PROMETHEUS_RETENTION_SIZE)'
        - '--web.enable-admin-api'
        - '--web.route-prefix=/'
        - '--web.external-url=http://prometheus.monitoring:9090'
        - '--log.level=debug'
        - '--query.max-concurrency=10'
        - '--query.timeout=2m'
        volumeMounts:
        - name: prometheus-tmp
          mountPath: /tmp
        - name: prometheus-data
          mountPath: /prometheus
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: prometheus-tmp
        emptyDir: {}
      - name: prometheus-data
        emptyDir: {}