name: Snyk Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  # Required for uploading SARIF files to GitHub Advanced Security
  security-events: write
  # Required for checkout and basic workflow operations
  contents: read
  # Required for pull request operations
  pull-requests: read
  # Required for workflow run telemetry and API access
  actions: read

jobs:
  snyk-pr-check:
    name: Snyk PR Security Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Snyk PR check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=requirements.txt
        command: test
    
    - name: Run Snyk Code PR check
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --severity-threshold=high
      continue-on-error: true

  snyk-python:
    name: Snyk Python Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=high --file=requirements.txt --sarif-file-output=snyk.sarif
      continue-on-error: true # Don't fail the workflow if vulnerabilities are found
    
    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('snyk.sarif') != '' # Only upload if SARIF file exists
      with:
        sarif_file: snyk.sarif

  snyk-docker:
    name: Snyk Docker Image Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v5
    
    - name: Build Docker image for scanning
      run: docker build -t business-intelligence:scan .
    
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: business-intelligence:scan
        args: --severity-threshold=high --file=Dockerfile --sarif-file-output=snyk-docker.sarif
      continue-on-error: true
    
    - name: Upload Snyk Docker results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('snyk-docker.sarif') != ''
      with:
        sarif_file: snyk-docker.sarif

  snyk-code:
    name: Snyk Code Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Run Snyk Code Analysis
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --severity-threshold=high --sarif-file-output=snyk-code.sarif
      continue-on-error: true
    
    - name: Upload Snyk Code results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('snyk-code.sarif') != ''
      with:
        sarif_file: snyk-code.sarif

  snyk-iac:
    name: Snyk Infrastructure as Code Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Run Snyk to check Kubernetes manifests
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: k8s/
        args: --severity-threshold=high --sarif-file-output=snyk-iac.sarif
      continue-on-error: true
    
    - name: Upload Snyk IaC results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('snyk-iac.sarif') != ''
      with:
        sarif_file: snyk-iac.sarif

  snyk-monitor:
    name: Monitor Dependencies with Snyk
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Monitor dependencies with Snyk
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: --file=requirements.txt --project-name=business_intelligence_platform